services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      - FLASK_APP=server.py
    # volumes:
    #   - .:/app

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5679:5678"  # Remap client debug port to avoid conflict with server
    depends_on:
      - server
    tty: true
    stdin_open: true
    # volumes:
    #   - .:/app
