services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "chat"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
      # - "5678:5678"
    environment:
      FLASK_APP: "server.py"
      SECRET_KEY: "dd0ab2cc9d93e63b5218b59e511ee316e4585f062dca1570e84a8c13fb08701c"
    # volumes:
    #   - .:/app

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    # ports:
    #   - "5679:5678"  # Remap client debug port to avoid conflict with server
    depends_on:
      - server
    tty: true
    stdin_open: true
    deploy:
      replicas: 2  # Number of client containers
    # volumes:
    #   - .:/app

volumes:
  postgres_data: